//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Srednja_skola_HCI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Srednja_skola_HCI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AdresaHeader {
            get {
                return ResourceManager.GetString("AdresaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BrisanjeHeader {
            get {
                return ResourceManager.GetString("BrisanjeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failing grades.
        /// </summary>
        public static string BrojNegativnihHeader {
            get {
                return ResourceManager.GetString("BrojNegativnihHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of students present.
        /// </summary>
        public static string BrojPrisutnihHeader {
            get {
                return ResourceManager.GetString("BrojPrisutnihHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of week classes.
        /// </summary>
        public static string BrojSedmicnihCasovaHeader {
            get {
                return ResourceManager.GetString("BrojSedmicnihCasovaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkRB {
            get {
                return ResourceManager.GetString("DarkRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DatumHeader {
            get {
                return ResourceManager.GetString("DatumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DatumRodjenjaHeader {
            get {
                return ResourceManager.GetString("DatumRodjenjaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting!.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added!.
        /// </summary>
        public static string DodavanjeMessage {
            get {
                return ResourceManager.GetString("DodavanjeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the execution. Check the uniqueness of the of the relevant data..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string GreenRB {
            get {
                return ResourceManager.GetString("GreenRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject ID.
        /// </summary>
        public static string IdPredmetaHeader {
            get {
                return ResourceManager.GetString("IdPredmetaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID.
        /// </summary>
        public static string IdSmjeraHeader {
            get {
                return ResourceManager.GetString("IdSmjeraHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ImeHeader {
            get {
                return ResourceManager.GetString("ImeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated!.
        /// </summary>
        public static string IzmjenaMessage {
            get {
                return ResourceManager.GetString("IzmjenaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string JezikLabel {
            get {
                return ResourceManager.GetString("JezikLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIN.
        /// </summary>
        public static string JIBHeader {
            get {
                return ResourceManager.GetString("JIBHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMN.
        /// </summary>
        public static string JMBHeader {
            get {
                return ResourceManager.GetString("JMBHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail:.
        /// </summary>
        public static string loginMailText {
            get {
                return ResourceManager.GetString("loginMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string loginPasswordText {
            get {
                return ResourceManager.GetString("loginPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LozinkaHeader {
            get {
                return ResourceManager.GetString("LozinkaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.
        /// </summary>
        public static string MailAdresaHeader {
            get {
                return ResourceManager.GetString("MailAdresaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string MailHeader {
            get {
                return ResourceManager.GetString("MailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MeniHeader {
            get {
                return ResourceManager.GetString("MeniHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. written exams.
        /// </summary>
        public static string MinimalniBrojPismenihProvjeraHeader {
            get {
                return ResourceManager.GetString("MinimalniBrojPismenihProvjeraHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. exams.
        /// </summary>
        public static string MinimalniBrojUsmenihProvjera {
            get {
                return ResourceManager.GetString("MinimalniBrojUsmenihProvjera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject name.
        /// </summary>
        public static string NazivPredmetaHeader {
            get {
                return ResourceManager.GetString("NazivPredmetaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School name.
        /// </summary>
        public static string NazivSkoleHeader {
            get {
                return ResourceManager.GetString("NazivSkoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name.
        /// </summary>
        public static string NazivSmjeraHeader {
            get {
                return ResourceManager.GetString("NazivSmjeraHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not teach any subject!.
        /// </summary>
        public static string NePredajePredmetMessage {
            get {
                return ResourceManager.GetString("NePredajePredmetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string OcjenaHeader {
            get {
                return ResourceManager.GetString("OcjenaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string OdjeljenjeHeader {
            get {
                return ResourceManager.GetString("OdjeljenjeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string PlataHeader {
            get {
                return ResourceManager.GetString("PlataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PodesavanjaHeader {
            get {
                return ResourceManager.GetString("PodesavanjaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string PogledajButton {
            get {
                return ResourceManager.GetString("PogledajButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string PolHeader {
            get {
                return ResourceManager.GetString("PolHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated exam.
        /// </summary>
        public static string PonovljenaHeader {
            get {
                return ResourceManager.GetString("PonovljenaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this row?.
        /// </summary>
        public static string PotvrdaBrisanjaMessage {
            get {
                return ResourceManager.GetString("PotvrdaBrisanjaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the data?.
        /// </summary>
        public static string PotvrdaPromjeneMessage {
            get {
                return ResourceManager.GetString("PotvrdaPromjeneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields must not be empty!.
        /// </summary>
        public static string PraznaPoljaError {
            get {
                return ResourceManager.GetString("PraznaPoljaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturers on the subject.
        /// </summary>
        public static string PredajeHeader {
            get {
                return ResourceManager.GetString("PredajeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string PredavaciHeader {
            get {
                return ResourceManager.GetString("PredavaciHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string PredmetiButton {
            get {
                return ResourceManager.GetString("PredmetiButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string PredmetiHeader {
            get {
                return ResourceManager.GetString("PredmetiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string PrezimeHeader {
            get {
                return ResourceManager.GetString("PrezimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professors.
        /// </summary>
        public static string ProfesoriButton {
            get {
                return ResourceManager.GetString("ProfesoriButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string ProfesoriHeader {
            get {
                return ResourceManager.GetString("ProfesoriHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade average.
        /// </summary>
        public static string ProsjekOcjenaHeader {
            get {
                return ResourceManager.GetString("ProsjekOcjenaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters are not valid. .
        /// </summary>
        public static string ProvjeraError {
            get {
                return ResourceManager.GetString("ProvjeraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string ProvjereButton {
            get {
                return ResourceManager.GetString("ProvjereButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string ProvjereHeader {
            get {
                return ResourceManager.GetString("ProvjereHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class is in range [1,4].
        /// </summary>
        public static string RazredError {
            get {
                return ResourceManager.GetString("RazredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string RazredHeader {
            get {
                return ResourceManager.GetString("RazredHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SacuvajButton {
            get {
                return ResourceManager.GetString("SacuvajButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string SkoleButton {
            get {
                return ResourceManager.GetString("SkoleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string SkoleHeader {
            get {
                return ResourceManager.GetString("SkoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string SmjeroviButton {
            get {
                return ResourceManager.GetString("SmjeroviButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string SmjeroviHeader {
            get {
                return ResourceManager.GetString("SmjeroviHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TelefonHeader {
            get {
                return ResourceManager.GetString("TelefonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string TemaLabel {
            get {
                return ResourceManager.GetString("TemaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TipHeader {
            get {
                return ResourceManager.GetString("TipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject type.
        /// </summary>
        public static string TipPredmetaHeader {
            get {
                return ResourceManager.GetString("TipPredmetaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration must be between 3 and 5 years..
        /// </summary>
        public static string TrajanjeGodinaError {
            get {
                return ResourceManager.GetString("TrajanjeGodinaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (years).
        /// </summary>
        public static string TrajanjeGodinaHeader {
            get {
                return ResourceManager.GetString("TrajanjeGodinaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string TrajanjeHeader {
            get {
                return ResourceManager.GetString("TrajanjeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pupils.
        /// </summary>
        public static string UceniciButton {
            get {
                return ResourceManager.GetString("UceniciButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string UceniciHeader {
            get {
                return ResourceManager.GetString("UceniciHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string VerifikovanHeader {
            get {
                return ResourceManager.GetString("VerifikovanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School type.
        /// </summary>
        public static string VrstaSkoleHeader {
            get {
                return ResourceManager.GetString("VrstaSkoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite.
        /// </summary>
        public static string WhiteRB {
            get {
                return ResourceManager.GetString("WhiteRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ZvanjeHeader {
            get {
                return ResourceManager.GetString("ZvanjeHeader", resourceCulture);
            }
        }
    }
}
